### ISSUE TITLE
HOW TO GET SCALE AND ORIENTATION WITH THIS METHOD ?

### ISSUE THREAD

**Issue by stilcrad** [laoyandujiang/S3Esti#1]
Great job！！how to use this network to directly obtain the direction and scale of a patch, such as I already know the coordinates of feature points

**Comment by laoyandujiang** [comment]
> Great job！！how to use this network to directly obtain the direction and scale of a patch, such as I already know the coordinates of feature points

Hi @stilcrad , thank you for your attention. The primary related function is "get_wrap_patches_multi" in the abso_esti_utils.py. The link is: [get_wrap_patches_multi](https://github.com/laoyandujiang/S3Esti/blob/89673946d1af074704dc5d40f9e85c1096214b97/abso_esti_model/abso_esti_utils.py#L60).
To my understanding, it will not be convenient for you to reorganize the code in this function to satisfy your requirements. I will write a new demo script to obtain the orientations and scales of some known feature points. This demo script will be uploaded to this repository this week. I will reply to you after it is completed. Thanks.

**Comment by stilcrad** [comment]
Thx!!!!!

**Comment by laoyandujiang** [comment]
> Great job！！how to use this network to directly obtain the direction and scale of a patch, such as I already know the coordinates of feature points

Hi @stilcrad. I have added a new demo script to estimate and visualize the keypoint scales and orientations of a given image. Please pull the latest code and use the demo script following README.md. Moreover, the latest code utilizes the latest "opencv-python" package, which is different from the previous version based on "opencv-contrib-python==3.xx". Please install the environment following the latest README.md, or update the "opencv-python" package if you have already configured the environment according to the old README.md.

Please let me know if there are other problems.
